import { appAngularIcon } from './angular';
import { appBmwIcon } from './bmw';
import { appDockerIcon } from './docker';
import { appFlutterIcon } from './flutter';
import { appNestIcon } from './nest';
import { appNrwlIcon } from './nrwl';
import { appReactIcon } from './react';
import { appSmaIcon } from './sma';
import { appSvelteIcon } from './svelte';
import { appVestasIcon } from './vestas';
import { appVueIcon } from './vue';
export const brandsIcons = [appAngularIcon, appBmwIcon, appDockerIcon, appFlutterIcon, appNestIcon, appNrwlIcon, appReactIcon, appSmaIcon, appSvelteIcon, appVestasIcon, appVueIcon];
